/**
 * Static params for partner routes (slugs + tab routes), precomputed from the
 * committed Supabase seed migration so `expo export` works without live
 * Supabase.
 *
 * The JSON is generated by `scripts/generate-partner-static.ts` (the first
 * step of the `mobile:build` target) and committed. Importing it statically
 * keeps this module free of Node APIs: a runtime `require('fs')` here breaks
 * either native bundling (when Metro sees it) or static web rendering (when
 * hidden from Metro, since the server bundle's require can't resolve node
 * builtins).
 */

import partnerStaticData from './partner-static-data.json';

type PartnerStaticInfo = { partnerSlug: string; tabSlugs: string[] };

const partners: PartnerStaticInfo[] = partnerStaticData.partners;

export function getPartnerStaticLandingParams(): { partnerSlug: string }[] {
  const seen = new Set<string>();
  const out: { partnerSlug: string }[] = [];

  for (const p of partners) {
    if (seen.has(p.partnerSlug)) continue;
    seen.add(p.partnerSlug);
    out.push({ partnerSlug: p.partnerSlug });
  }

  return out;
}

export function getPartnerStaticTabParams(): { partnerSlug: string; tab: string }[] {
  const seen = new Set<string>();
  const out: { partnerSlug: string; tab: string }[] = [];

  for (const p of partners) {
    for (const tab of p.tabSlugs) {
      const key = `${p.partnerSlug}:${tab}`;
      if (seen.has(key)) continue;
      seen.add(key);
      out.push({ partnerSlug: p.partnerSlug, tab });
    }
  }

  return out;
}
