#!/usr/bin/env python3
"""
Scrape content from lincolntwp.com via Wayback Machine and convert to Markdown.
Reads sitemap.json generated by discover-structure.py and extracts content from each page.
"""

import json
import os
import re
import time
from datetime import datetime
from urllib.parse import urlparse
from bs4 import BeautifulSoup
from markdownify import markdownify as md
import requests


def load_sitemap(filename='sitemap.json'):
    """Load the sitemap generated by discover-structure.py."""
    filepath = f"scripts/scraper/{filename}"
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)


def clean_content(soup):
    """Remove navigation, header, footer, and other chrome from the page."""
    # Remove common navigation elements
    for element in soup.find_all(['nav', 'header', 'footer']):
        element.decompose()

    # Remove script and style tags
    for element in soup.find_all(['script', 'style']):
        element.decompose()

    # Remove wayback machine toolbar
    for element in soup.find_all(id=re.compile('wm-')):
        element.decompose()
    for element in soup.find_all(class_=re.compile('wm-')):
        element.decompose()

    return soup


def extract_main_content(html):
    """Extract the main content from the HTML."""
    soup = BeautifulSoup(html, 'html.parser')

    # Clean up the page
    soup = clean_content(soup)

    # Try to find main content area
    # Common patterns: <main>, <article>, <div id="content">, etc.
    main_content = (
        soup.find('main') or
        soup.find('article') or
        soup.find(id='content') or
        soup.find(id='main') or
        soup.find(class_='content') or
        soup.find('body')  # Fallback to body
    )

    if main_content:
        return str(main_content)

    return str(soup)


def html_to_markdown(html):
    """Convert HTML content to Markdown."""
    # Convert to markdown
    markdown = md(
        html,
        heading_style="ATX",
        bullets="-",
        strip=['script', 'style']
    )

    # Clean up excessive whitespace
    markdown = re.sub(r'\n\n\n+', '\n\n', markdown)
    markdown = markdown.strip()

    return markdown


def generate_slug(url):
    """Generate a slug from the URL."""
    parsed = urlparse(url)
    path = parsed.path

    # Remove leading/trailing slashes
    path = path.strip('/')

    # If it's the homepage
    if not path or path == 'index.htm' or path == 'index.html':
        return 'index'

    # Remove file extensions
    path = re.sub(r'\.(htm|html)$', '', path)

    # Replace special characters with hyphens
    slug = re.sub(r'[^a-z0-9]+', '-', path.lower())
    slug = slug.strip('-')

    return slug if slug else 'index'


def generate_frontmatter(page_info, order=None):
    """Generate YAML frontmatter for the markdown file."""
    title = page_info.get('title', 'Untitled').replace('"', '\\"')
    description = page_info.get('description', '').replace('"', '\\"')

    # Use site name from title if available
    if ' - ' in title:
        title = title.split(' - ')[0].strip()

    frontmatter = f'''---
title: "{title}"
description: "{description}"
lastUpdated: "{datetime.now().strftime('%Y-%m-%d')}"
'''

    if order is not None:
        frontmatter += f'order: {order}\n'

    frontmatter += '---\n\n'

    return frontmatter


def scrape_page(page_info, order=None):
    """Scrape a single page and convert to Markdown."""
    wayback_url = page_info['wayback_url']
    print(f"Scraping: {page_info['title']}")

    try:
        response = requests.get(wayback_url, timeout=15)
        response.raise_for_status()

        # Extract main content
        main_html = extract_main_content(response.text)

        # Convert to markdown
        markdown_content = html_to_markdown(main_html)

        # Generate frontmatter
        frontmatter = generate_frontmatter(page_info, order)

        # Combine frontmatter and content
        full_content = frontmatter + markdown_content

        # Generate slug for filename
        slug = generate_slug(page_info['url'])

        return {
            'slug': slug,
            'content': full_content,
            'success': True
        }

    except Exception as e:
        print(f"Error scraping {wayback_url}: {e}")
        return {
            'slug': generate_slug(page_info['url']),
            'content': None,
            'success': False,
            'error': str(e)
        }


def save_markdown_file(slug, content, directory='src/content/pages'):
    """Save markdown content to a file."""
    # Create directory if it doesn't exist
    os.makedirs(directory, exist_ok=True)

    filename = f"{slug}.md"
    filepath = os.path.join(directory, filename)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"  Saved: {filepath}")


def scrape_all_pages():
    """Scrape all pages from the sitemap."""
    # Load sitemap
    sitemap = load_sitemap()
    pages = sitemap['pages']

    print(f"Scraping {len(pages)} pages...")
    print("=" * 60)

    # Create content directory
    os.makedirs('src/content/pages', exist_ok=True)

    # Track results
    successful = 0
    failed = 0

    # Scrape each page
    for i, page in enumerate(pages):
        result = scrape_page(page, order=i + 1)

        if result['success']:
            save_markdown_file(result['slug'], result['content'])
            successful += 1
        else:
            failed += 1
            print(f"  Failed: {result.get('error', 'Unknown error')}")

        # Be respectful - add delay between requests
        time.sleep(2)

    print("\n" + "=" * 60)
    print(f"Scraping complete!")
    print(f"Successful: {successful}")
    print(f"Failed: {failed}")
    print(f"\nContent saved to src/content/pages/")


if __name__ == '__main__':
    print("Starting content scraping...")
    print("=" * 60)

    try:
        scrape_all_pages()
        print("\n✓ Content extraction complete!")
    except FileNotFoundError:
        print("\n✗ Error: sitemap.json not found!")
        print("Please run discover-structure.py first to generate the sitemap.")
    except Exception as e:
        print(f"\n✗ Error: {e}")
